apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mynginxclaim
  namespace: aitrain
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

